.TH usr/games/BuenComer

.SH NAME
BuenComer

.SH SYNOPSIS
BuenComer es un videojuego creado por el Equipo de Huayra GNU/Linux para
aprender jugando sobre alimentación.

.SH DESCRIPTION

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

.PP

.SH FILES
https://github.com/HuayraLinux/BuenComer

.SH AUTHOR
Realizado por Diego Accorinti (@diegoacco) para Huayra GNU/Linux
<diegoacco@gmail.com>
2017 Software libre bajo licencia GPL3 
